### PR TITLE
initial selftest for android appium

### PR DESCRIPTION
**Pull request by trimai3001**
Hello Thomas,
I have initialized some test cases for Android Appium.
Please help me to review this.
Thank you

### CODE REVIEW

**Review by test-fullautomation — COMMENTED** [review]
Hi Tri,
looks very good!
Where/How do you startup emulator and testapp?
Thank you,
 Thomas

**Review by test-fullautomation — COMMENTED** [review]
Hi Tri,
please check my comment.
Thank you,
 Thomas

**Comment by trimai3001** [comment]
Hi Thomas,
I'm currently working on starting and closing the emulator and the testapp. 
I'll include these changes in the next commit.
Thank you,
Tri

**Comment by test-fullautomation** [comment]
> Hi Thomas, I'm currently working on starting and closing the emulator and the testapp. I'll include these changes in the next commit. Thank you, Tri

Hi @trimai3001 , @ngoan1608 ,
O.K. very good. Then I wait for the next commit.

Also the pipelines need to install the emulator?
SelfTest APK need to be installed, ...

Thank you,
 Thomas

**Pull request merged**
