### PR TITLE
update start and close emulator

### PR DESCRIPTION
**Pull request by trimai3001**

### CODE REVIEW

**Review by test-fullautomation — APPROVED** [review]
Hi Tri,
looks good to me!
Thank you,
 Thomas

**Review by test-fullautomation — CHANGES_REQUESTED** [review]
Hi Tri,

what I miss is the codes for the TMLSelfTest.apk.
Please add this, too.
In a second step we should also rename it to "SelfTest.apk".

Thank you,
 Thomas

**Comment by test-fullautomation** [comment]
Hi @trimai3001 ,
still I miss is the codes for the TMLSelfTest.apk.
Please add this, too.
In a second step we should also rename it to "SelfTest.apk".

release_info is missing, too.

Thank you,
 Thomas

**Comment by test-fullautomation** [comment]
Hi @trimai3001 ,
very good, apk sources are there now.

Holger already added the release_info tool support (i already merged it). Please rebase and extend the release_info file according to your changes.

Last wish:
There are a lot of images with "TML" inside. Please make all images new with "RF AIO" (with space after RF) instead of TML.

@ngoan1608 : Is it a big effort to build the apk new with the new images and rename it to SelfTest.apk? If not, then we should do this also.

Thank you,
 Thomas

**Comment by ngoan1608** [comment]
> Hi @trimai3001 , very good, apk sources are there now.
> 
> Holger already added the release_info tool support (i already merged it). Please rebase and extend the release_info file according to your changes.
> 
> Last wish: There are a lot of images with "TML" inside. Please make all images new with "RF AIO" (with space after RF) instead of TML.
> 
> @ngoan1608 : Is it a big effort to build the apk new with the new images and rename it to SelfTest.apk? If not, then we should do this also.
> 
> Thank you, Thomas

Hi Thomas, 

It will not take too much effort, I have tried to rebuild this morning but there is issue with Gradle sync for building (version issues).
I am working on this topic to update source code to remove TML and Bosch-related stuffs.
As soon as the build is successful, I will add all changes into PR.

Thank you,
Ngoan

**Comment by ngoan1608** [comment]
Hi Thomas,

I have update the project source code and remove the sensitive information.
Besides, the icon and package name have been changed to **com.testfullautomation.selftest**.
The result *.apk file has also uploaded with new version **1.1.0**

Hi @trimai3001 ,
Please update new package name if it is used in robot test file.

Thank you,
Ngoan

**Comment by test-fullautomation** [comment]
Hi @ngoan1608 ,
very good!
I still find TML e.g. here: [helpers/Android/Selftest/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png](https://github.com/test-fullautomation/robotframework-selftest/pull/7/files#diff-717236aecd462bff90c42726274bc244fa5010f4a029b16d19f8c4a9fb2d629f)
Thank you,
 Thomas

**Comment by ngoan1608** [comment]
Hi Thomas,

I have removed them in latest commit.

Thank you,
Ngoan

**Pull request merged**
